name: Snyk
on: workflow_dispatch
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Running Snyk 
        continue-on-error: true 
        env:
          SNYK_CFG_ORG: ${{ secrets.SNYK_CFG_ORG }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          echo Downloading    
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          ./snyk code test --sarif-file-output=snyk.sarif
          ls -l snyk.sarif
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
